### ISSUE TITLE
data fetching for silverchair 

### ISSUE THREAD

**Issue by shyamkhakhar9** [ezpaarse-project/ezpaarse-platforms#183]
Below is the PDF url of the silverchair and I want to process it and fetch the data for it.
Can you help me @nojhamster , @pseudom  how the token gets generated so that I can process the url or Can I fetch the data from the unique identification number of the document (in the beolw case it is g46100) without the token?

https://watermark.silverchair.com/g46100.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAgAwggH8BgkqhkiG9w0BBwagggHtMIIB6QIBADCCAeIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIuPKDSYh5QRoR-vIAgEQgIIBs95z_5H2cA9pAWI5vn_D_e1pPK8jENUr8NSiA10cvXBkiyHKeTLDaFLRttXmDQze56mzriM9mkMoQyXIUdiE9s7IRmCR6R73qqywu_x4hKZ2O--hKAowp8dNQnWvhqpAEhaM97k8ymumoTqUGOlFWBlIpcZZJnIY39hl479JvNyqmaBe8klPGzCAqsokb0nNr3GSoAnOeV1YGCFIZXFvly5_4ZJPOYDBIlxsWuPoB17jm9GKlJc9JJQfno5cDRUjWpsJqT-_R1sqbbCp4-eVN1-9mvjt7FlTFMDOvgtGcjeom_N_HN4xb_qPXo3D6RWgilzOdz0uy9IeMiAUSGCavX-i7U7c80SOM1qCWtXNKG0f551U0RhzXHA89OYD-Kc6j7RNwmPxL2afEj8Gg-oCx0Zut1eOwtJIKeOe9ChgyTuBV1Ef32eEnYMbBXaqnDdl37uJx06jfHCy1Fxu_6no9noOBi2VLYxyA-nxATB1YJoyjxuW_nH5du33wG_k9Q0xyG_Aj3XmIeuOsV5tcki4JArdBHaOcW2aZAOt8nFrQq7Rr7j0oigOkudEk-gPVKaUD9FOpA

**Comment by tporquet** [comment]
Hello,
I don't think the token will be useful in this case, as it is an element that is going to be different everytime you access the document (and more related to your navigation than to the resource that is accessed).
We could use the unique identification number of the document, as the unit_id but i'm afraid we won't be able to link it to bibliographical information.

Our analysis for the Silverchair platform is on:
http://analyses.ezpaarse.org/platforms/57fb57bc94980fc7c97ac721

Can you explain what type of resource you access with the URL you pasted: is it a journal article? From which journal?

**Comment by shyamkhakhar9** [comment]
@tporquet yes it's a article and I need to fetch the doi of the article using the parser.
So is there any way by which we can fetch the doi of the article using the unit_id ?

**Comment by tporquet** [comment]
I'm afraid we can't in this particular case: it would need a matching file (at the article level - unit_id) provided by Silverchair. The best we can hope for is a KBART file (at the journal title level - journal_id) or a DOI explicitly placed in the URL.
The only thing we can make ezpaarse tell in this case is : an undefined article in PDF has been accessed.
