### ISSUE TITLE
Jstor "path=adsf" url parameter

### ISSUE THREAD

**Issue by craigboman** [ezpaarse-project/ezpaarse-platforms#256]
The path= url parameter in jstor urls are actually base64 encoded s3 buckets paths. Any reason we'd want to know what the s3 bucket path is? For instance the following url path:
https://www.jstor.org:443/stable/get_image/23023615?**path=czM6Ly9zZXF1b2lhLWNlZGFyL2NpZC1wcm9kLTEvOGNkOTAzMjcvY2I1NC8zM2I5Lzk1YmUvOGNiODAyOThkYmYyL2kyMzAyMzI2MC8yMzAyMzYxNS9pbWFnZXMvcGFnZXMvZHRjLjM0LnRpZi5qcGc**

path= decoded: s3://sequoia-cedar/cid-prod-1/940bde6b/ecbc/31bd/8093/9c6b189ea3a9/i40053719/41198468/graphic/pages/dtc.49.tif.jpg

**Comment by tporquet** [comment]
This URL parameter doesn't indeed seem to contain useful information for us.
It looks like an S3 Amazon asset, so maybe a book cover or an illustration. 
Thank you for the heads up!
