### ISSUE TITLE
Additional edge cases for libertpub.com date extraction

### ISSUE THREAD

**Issue by ctgraham** [ezpaarse-project/ezpaarse-platforms#720]
Beyond the reported edge cases in #407 , `mal` has additional URI which match the parser but where the terminal string does not represent a date.  For example:
```
127.0.0.1 nobody@pitt.edu 6dZtApLJwt5cElk [12/Mar/2023:21:00:49 -0400] "GET https://www.liebertpub.com:443/doi/pdf/10.1089/DERM.0000000000000905 HTTP/1.1" 200 377913
127.0.0.1 nobody@pitt.edu 6dZtApLJwt5cElk [12/Mar/2023:21:02:54 -0400] "GET https://www.liebertpub.com:443/doi/pdf/10.1089/DERM.0000000000000954 HTTP/1.1" 200 399954
127.0.0.1 nobody@pitt.edu r8iX0BfXC6td3UM [28/Mar/2023:09:00:25 -0400] "GET https://www.liebertpub.com:443/doi/pdf/10.1097/DER.0000000000000524?download=true HTTP/1.1" 200 131881
```

**Comment by oxypomme** [comment]
Just to be sure, the issue is that in the case where the terminal string does not represent a date, the parser returns a wrong  publication date (like 0000 in those examples) ?

**Comment by ctgraham** [comment]
>  in the case where the terminal string does not represent a date, the parser returns a wrong publication date

Yes, correct!
