### ISSUE TITLE
the colon (:) character in test filename is causing issue when checking out the file in git under windows platform

### ISSUE THREAD

**Issue by ThomasMic** [ezpaarse-project/ezpaarse-platforms#850]
il n'est pas possible de gérer des noms de fichiers avec des caractères ':' (deux points) sur les file systems windows, il y erreur lors du check-out de ce fichier par ex. ezupw/test/ezupw.2021-09-30.csv:Zone.Identifier et je doute que l'on puisse lancer les tests sous windows du coup.

**Comment by felixleo22** [comment]
C'est un fichier qui a été commit par erreur, il n'est pas utilisé. On va le supprimer et vous devriez ne plus avoir de problème.

**Comment by ThomasMic** [comment]
ah super ! j'avais une pull request en attente à cause de ça.
