### ISSUE TITLE
Domain in Manifest for PolicyMap [pm]

### ISSUE THREAD

**Issue by AGCooper** [ezpaarse-project/ezpaarse-platforms#98]
I just remembered the domain in the manifest.json for PolicyMap (pm) is Emory University specific, i.e. emory.policymap.com (or something like that). Not sure how to handle that. Any thoughts?

Best

**Comment by tporquet** [comment]
We'll add more university specific domains at their request (except if you already know some of them that we could already include in the manifest).
Thanks!
